services:
  app:
    build: app/
    command: python -u ./main.py
    ports:
      - "8000:8000"
    links:
      - db
    networks:
      - net
    depends_on:
      - db

  db:
    image: mongo:latest
    hostname: avito_mongodb
    environment:
      - MONGO_INITDB_DATABASE=avito_db
    networks:
      - net

networks:
  net: